### ISSUE TITLE
Missing runtime dependencies as also licence information

### ISSUE THREAD

**Issue by yegorich** [n-s-f/hmm#1]
The project depends on SciPy, but this is not reflected in setup.py. Could you also add a LICENSE file?

**Comment by n-s-f** [comment]
Great ideas! I'd be happy to accept a pull request.

**Comment by yegorich** [comment]
@n-s-f As for the licence you're to decide which one you would like to use. I prefer something permissive like [MIT](https://spdx.org/licenses/MIT.html).

**Comment by n-s-f** [comment]
Great, done.
